### ISSUE TITLE
dataset about dsutils

### ISSUE THREAD

**Issue by ninanxiaoguai** [DataCanvasIO/Hypernets#35]
an error about "from hypernets.frameworks.ml.datasets import dsutils", I think it should be "from deeptables.datasets import dsutils".

**Comment by jackguagua** [comment]
@ninanxiaoguai Thanks for your feedback, some docs are not synchronized with codes, we will deal with it as soon as possible.

**Comment by lixfz** [comment]
Fixed.

Use `from hypernets.tabular.datasets import dsutils` pls.
