### ISSUE TITLE
window pip fail.

### ISSUE THREAD

**Issue by zhangxjohn** [DataCanvasIO/Hypernets#53]
ERROR: Complete output from command 'D:\Anaconda\Anaconda3\python.exe' -u -c 'import setuptools, tokenize;__file__='"'"'C:\\Users\\John\\AppData\\Local\\Temp\\pip-install-4hgmcjg1\\python-geohash\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d 'C:\Users\John\AppData\Local\Temp\pip-wheel-gijlszf9' --python-tag cp37:
  ERROR: running bdist_wheel
  running build
  running build_py
  creating build
  creating build\lib.win-amd64-3.7
  copying geohash.py -> build\lib.win-amd64-3.7
  copying quadtree.py -> build\lib.win-amd64-3.7
  copying jpgrid.py -> build\lib.win-amd64-3.7
  copying jpiarea.py -> build\lib.win-amd64-3.7
  running build_ext
  building '_geohash' extension
  error: Microsoft Visual C++ 14.0 is required. Get it with "Microsoft Visual C++ Build Tools": https://visualstudio.microsoft.com/downloads/
  ----------------------------------------
  ERROR: Failed building wheel for python-geohash
  Running setup.py clean for python-geohash
Failed to build python-geohash
ERROR: spyder 3.3.6 requires pyqt5<5.13; python_version >= "3", which is not installed.
ERROR: spyder 3.3.6 requires pyqtwebengine<5.13; python_version >= "3", which is not installed.
ERROR: distributed 2021.11.1 has requirement dask==2021.11.1, but you'll have dask 2.1.0 which is incompatible.
ERROR: woodwork 0.9.0 has requirement pandas>=1.3.0, but you'll have pandas 1.2.3 which is incompatible.
ERROR: featuretools 1.2.0 has requirement dask[dataframe]>=2021.10.0, but you'll have dask 2.1.0 which is incompatible.
ERROR: featuretools 1.2.0 has requirement pandas<2.0.0,>=1.3.0, but you'll have pandas 1.2.3 which is incompatible.
Installing collected packages: psutil, pyyaml, tblib, distributed, woodwork, featuretools, python-geohash, hypernets
  Found existing installation: psutil 5.6.3
    Uninstalling psutil-5.6.3:
      Successfully uninstalled psutil-5.6.3
  Found existing installation: PyYAML 5.1.1
ERROR: Cannot uninstall 'PyYAML'. It is a distutils installed project and thus we cannot accurately determine which files belong to it which would lead to only a partial uninstall.

**Comment by Enpen** [comment]
Hi @zhangxjohn , thanks for using hypernets, From your error logs,  it's seem a version conflict. You can just  try 
```
 conda install -c conda-forge python-geohash
 conda install pyaml==20.4.0
 conda install PyYAML==5.4.1
 pip install hypernets
```
And Please let me know if those codes work

**Comment by Enpen** [comment]
Let me close the issue because we couldn't get further updates for while
