### ISSUE TITLE
A suggestion for GreedyEnsemble

### ISSUE THREAD

**Issue by zhangxjohn** [DataCanvasIO/Hypernets#88]
On line 107 of voting's code, i.e. 
`if self.ensemble_size <= 0:  size = predictions.shape[1]`

Is it possible to replace it with `self.ensemble_size <= 0 or predictions.shape[1] < self.ensemble_size:  size = predictions.shape[1]`?

**Comment by lixfz** [comment]
By convention the number of 0 or -1 means it should be infered by the module itself, a position number means it is set by the caller. So it is reasonable to control the number of `ensemble_size` by caller.
