### ISSUE TITLE
There may be some issues with the code

### ISSUE THREAD

**Issue by jialwdjial** [DataCanvasIO/Hypernets#98]
I noticed that using the `pip install hyperkeras` command did not download the hyperkeras related packages （i used python3.8）, so I directly downloaded and referenced the hyperkeras code library, and then used the code about defined in the CNN neural architecture search in the document you provided. However, I found the following error, which part of the definition is missing. I hope to receive your reply as soon as possible. Thank you
![%U~DPG%RQ_U7M4`_B9`I7A7](https://github.com/DataCanvasIO/Hypernets/assets/90499581/b660c501-ed85-4b9e-a8fc-c87178c0993b)
![{8O71K VABXIJLD0A~R%(L8](https://github.com/DataCanvasIO/Hypernets/assets/90499581/d88e07c3-2811-4246-9e15-3daae02cf897)

 
笔

**Comment by lixfz** [comment]
Hi,
Thanks for your message! We fix it in the lastest source code, and will release it later.

Currently, you can fix it with the command:

```
 pip install  --force-reinstall --no-deps  git+https://github.com/DataCanvasIO/Hypernets
```
